#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apache2'
cookbook 'apt'
cookbook 'build-essential'
cookbook 'git'
cookbook 'openssl'
cookbook 'python'
cookbook 'python-data', :github => 'bsweger/python-data'
